/***************************************************************************
 *
 *             INFORMIX SOFTWARE, INC.
 *
 *                PROPRIETARY DATA
 *
 *  THIS DOCUMENT CONTAINS TRADE SECRET DATA WHICH IS THE PROPERTY OF 
 *  INFORMIX SOFTWARE, INC.  THIS DOCUMENT IS SUBMITTED TO RECIPIENT IN
 *  CONFIDENCE.  INFORMATION CONTAINED HEREIN MAY NOT BE USED, COPIED OR 
 *  DISCLOSED IN WHOLE OR IN PART EXCEPT AS PERMITTED BY WRITTEN AGREEMENT 
 *  SIGNED BY AN OFFICER OF INFORMIX SOFTWARE, INC.
 *
 *  THIS MATERIAL IS ALSO COPYRIGHTED AS AN UNPUBLISHED WORK UNDER
 *  SECTIONS 104 AND 408 OF TITLE 17 OF THE UNITED STATES CODE. 
 *  UNAUTHORIZED USE, COPYING OR OTHER REPRODUCTION IS PROHIBITED BY LAW.
 *
 *
 *  Title:  sqlca.h
 *  Sccsid: @(#)sqlca.h 9.1.1.1 1/11/92  15:55:49
 *  Description:
 *      SQL Control Area
 *
 ***************************************************************************
 */

#pragma pack(push, 4)

#ifndef SQLCA_INCL
#define SQLCA_INCL

struct sqlca_s
	{
	long sqlcode;
	char sqlerrm[72]; /* error message parameters */
	char sqlerrp[8];
	long sqlerrd[6];
			/* 0 - estimated number of rows returned */
			/* 1 - serial value after insert or  ISAM error code */
			/* 2 - number of rows processed */
			/* 3 - estimated cost */
			/* 4 - offset of the error into the SQL statement */
			/* 5 - rowid after insert  */
	struct sqlcaw_s
	{
	char sqlwarn0; /* = W if any of sqlwarn[1-7] = W */
	char sqlwarn1; /* = W if any truncation occurred or
				database has transactions */
	char sqlwarn2; /* = W if a null value returned or
				ANSI database */
	char sqlwarn3; /* = W if no. in select list != no. in into list or
				turbo backend */
	char sqlwarn4; /* = W if no where clause on prepared update, delete or
				incompatible float format */
	char sqlwarn5; /* = W if non-ANSI statement */
	char sqlwarn6; /* reserved */
	char sqlwarn7; /* reserved */
	} sqlwarn;
	};

/* NOTE: 4gl assumes that the sqlwarn structure can be defined as
 *  sqlawarn -- an 8 character string, because single-char
 *  variables are not recognized in 4gl.
 *
 * If this structure should change, the code generated by 4gl compiler
 *  must also change
 */

#ifdef VMS
noshare
#endif /* VMS */

/***********                    samh 12/22      multiple app sqli */
extern struct sqlca_s sqlca;

extern long SQLCODE;
/*****************/

#define SQLNOTFOUND 100
#endif /* SQLCA_INCL */

#pragma pack(pop, 4)

